FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:0.2.5

ENV RUST_BACKTRACE=1

# Install dbus and xcb dev packages
RUN apt-get update && \
    apt-get install -y \
    libdbus-1-dev \
    libxcb1-dev \
    libx11-dev \
    libxi-dev \
    libxext-dev \
    libxtst-dev \
    && rm -rf /var/lib/apt/lists/*
